version: '3.1'

services:
  db:
    image: mysql:8.1.0
    volumes:
      - dbbase:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: sb_forum

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8085:80

volumes:
  dbbase: